# Site settings
title:
email: "maurycymoczulski@gradienthouse.pl"
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "gradienthouse.github.io" # the base hostname & protocol for your site

collections:
  projects:
    output: true

linkedin_username: gradienthouse

# Build settings
markdown: kramdown
